### ISSUE TITLE
STM32 support

### ISSUE THREAD

**Issue by CodeOn-ArK** [arm-university/Digital-Signal-Processing-Education-Kit#1]
Is the course content extendable to STM32F407 based discovery boards?

**Comment by franciscatan-armedu** [comment]
Hi. This course content could be used for the STM32F407, however, it would not work out of the box because you would need to manually port to the correct board support packages in Keil. 

We do have an older DSP course content specific for STM32F407 Discovery board that we are currently not actively maintaining. This older kit would requite a Wolfson Audio Card and may contain references to non-inclusive language; we will be updating future courses with newer terms as those terms are agreed and ratified with the wider community. To obtain this specific older kit material, please obtain the F4 version in https://community.arm.com/aup/dsp-st-discovery/

We welcome any modifications, fork or clone for this material should you want to update the existing material in GitHub to be extendable of the F4 version. See [LICENSE.md](https://github.com/arm-university/Digital-Signal-Processing-Education-Kit/blob/main/License/LICENSE.md) for the complete license.
